# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - master
     - releases/*
 paths:
   include:
     - clusterconfiguration/compliance/ComplianceWebHooks/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: FuncToolsInstaller@0
  inputs:
    version: 'latest'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      ls $(Build.ArtifactStagingDirectory)
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.ArtifactStagingDirectory)'

    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'PwC MSDN'
    appType: 'functionApp'
    appName: 'msreadycompliance'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
