# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - master
     - releases/*
 paths:
   include:
     - clusterconfiguration/compliance/ComplianceWebHooks/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: FuncToolsInstaller@0
  inputs:
    version: 'latest'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/clusterconfiguration/compliance/ComplianceWebHooks/'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)/clusterconfiguration/compliance/ComplianceWebHooks/'
    customCommand: 'run build:production'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/clusterconfiguration/compliance/ComplianceWebHooks/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: 'ComplianceWebHooks-$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/ComplianceWebHooks-$(Build.BuildId).zip'
    ArtifactName: 'deploy'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'deploy'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'PwC MSDN'
    appType: 'functionApp'
    appName: 'msreadycompliance'
    package: '$(System.ArtifactsDirectory)/deploy/ComplianceWebHooks-$(Build.BuildId).zip'
    deploymentMethod: 'auto'
