apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: nopublicip
  namespace: compliance
  annotations:
    cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca
webhooks:
  - name: nopublic.msready.com
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - services
    failurePolicy: Fail
    clientConfig:
      service:
        name: policy-service
        namespace: policies
        path: /api/nopublicip
      #url: "https://msreadycompliance.azurewebsites.net/api/NoPublicIp"