apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
    environment: dev
    team: infra
  annotations:
    test: app
  name: test-app-bad-service
  namespace: infra-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: test-app
    environment: dev
    team: infra
  sessionAffinity: None
  type: LoadBalancer